spring:
  docker:
    compose:
      stop:
        command: down
  sql:
    init:
      mode: always
jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
server:
  http2:
    enabled: true
  ssl:
    key-store: /home/akosarev/tmp/ssl/keystore/localhost.p12
    key-store-password: password
    key-alias: localhost
  port: 8443
logging:
  level:
    org.springframework.security: trace